// PDF export using jspdf
import type { DailyLog } from '@/types';
import { generateDoctorSummary } from './insights-engine';

export async function generatePDFReport(
  logs: DailyLog[],
  days: number
): Promise<Blob | null> {
  try {
    const jsPDF = (await import('jspdf')).default;

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = margin;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(13, 115, 119); // primary color
    doc.text('POTSTracker', margin, y);
    y += 8;

    doc.setFontSize(12);
    doc.setTextColor(107, 114, 128);
    doc.text('Dysautonomia Diary - Doctor Visit Report', margin, y);
    y += 10;

    // Horizontal line
    doc.setDrawColor(13, 115, 119);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Summary text
    const summary = generateDoctorSummary(logs, days);
    const lines = summary.split('\n');

    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);

    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }

      // Section headers
      if (
        line === line.toUpperCase() &&
        line.trim().length > 0 &&
        !line.startsWith(' ') &&
        !line.startsWith('---')
      ) {
        y += 3;
        doc.setFontSize(12);
        doc.setTextColor(13, 115, 119);
        doc.text(line, margin, y);
        doc.setFontSize(10);
        doc.setTextColor(31, 41, 55);
      } else if (line.startsWith('---')) {
        y += 3;
        doc.setDrawColor(229, 231, 235);
        doc.line(margin, y, pageWidth - margin, y);
      } else {
        doc.text(line, margin, y);
      }
      y += 5;
    }

    // Footer
    y += 5;
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by POTSTracker on ${new Date().toLocaleDateString()}`,
      margin,
      y
    );

    return doc.output('blob');
  } catch (error) {
    console.error('PDF generation failed:', error);
    return null;
  }
}
